version: '3.8'

volumes:
  postgres-data:
  mysql-data:

networks:
  app-network: # Define una red personalizada
    driver: bridge

services:
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inventario
      POSTGRES_HOSTNAME: postgresdb

      # MYSQL_USER: admin
      # MYSQL_PASSWORD: root
      # MYSQL_DATABASE: inventario
      # MYSQL_HOSTNAME: mysqldb

    volumes:
      - ../..:/workspaces:cached
      
    command: sleep infinity

    networks:
      - app-network

  db:
    container_name: postgresdb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inventario

    networks:
      - app-network

  # mysql:
  #   container_name: mysqldb
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: inventario
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: root

  #   networks:
  #     - app-network
